# TEMPORARY -- temper left half as a peripheral of the pacino right central
# (see boards/shields/temper_pacino/temper_pacino_left.overlay for the whole story)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_POINTING=y
